#
# Example .tmux.conf
#
# By Nicholas Marriott. Public domain.
#

set -g default-terminal "screen-256color"

#renumber windows after close;
set -g renumber-windows on

set-option -g default-command bash
# Some tweaks to the status line
# set -g status-right "%H:%M"
# # set -g window-status-current-style "underscore"
# set -g window-status-current-style ""
# setw -g window-status-current-format '#[fg=blue,bg=black, nobold] #I:#[fg=blue,bg=black, bold]#W#[fg=blue,bg=black, nobold]#F'
# # setw -g window-status-format '#[fg=blue,bg=black, nobold] #I:#[fg=blue,bg=black, bold]#W#[fg=blue,bg=black, nobold]#F'
# setw -g window-status-format '#[fg=white,bg=black] #I:#W#F'
# set -g status-style bg='cyan'

# If running inside tmux ($TMUX is set), then change the status line to red
%if #{TMUX}
set -g status-bg red
%endif

#unixPorn design:
#  modes
setw -g clock-mode-colour colour5
setw -g mode-style 'fg=colour1 bg=colour18 bold'

# panes
set -g pane-border-style 'fg=colour19 bg=colour0'
set -g pane-active-border-style 'bg=colour0 fg=colour9'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=colour233 fg=colour250 dim'
set -g status-left '#[fg=colour249][#S] '
set -g status-right '#[fg=colour232,bg=colour241] %d/%m #[fg=colour232,bg=colour245] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-style 'fg=colour209 bg=colour240 bold'
setw -g window-status-current-format ' #I#[fg=colour251]:#[fg=colour255]#W#[fg=colour249]#F '

setw -g window-status-style 'fg=colour9 bg=colour234'
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

setw -g window-status-bell-style 'fg=colour255 bg=colour1 bold'

# messages
set -g message-style 'fg=colour9 bg=colour234 bold'

# Enable RGB colour if running in xterm(1)
set-option -sa terminal-overrides ",xterm*:Tc"
# No bells at all
set -g bell-action none

# Keep windows around after they exit
set -g remain-on-exit on

# Change the prefix key to C-a
set -g prefix C-space
unbind C-b
bind C-a send-prefix

# Turn the mouse on, but without copy mode dragging
set -g mouse on
unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane

# Pane-movement
bind-key h select-pane -L
bind-key l select-pane -R
bind-key j select-pane -D
bind-key k select-pane -U
bind-key tab select-pane -t :.+
bind-key btab select-pane -t :.-
#bind-key resize-pane -D (Resizes the current pane down)
#bind-key resize-pane -U (Resizes the current pane upward)


# reload config
bind r source-file ~/.tmux.conf

# A key to toggle between smallest and largest sizes if a window is visible in
# multiple places
bind F set -w window-size

# Keys to toggle monitoring activity in a window and the synchronize-panes option
bind m set monitor-activity
bind y set synchronize-panes\; display 'synchronize-panes #{?synchronize-panes,on,off}'

# Create a single default session - because a session is created here, tmux
# should be started with "tmux attach" rather than "tmux new"
